name = "BinaryClassificationTools"
uuid = "cd7c4aec-4cd0-11ea-3b51-c118b6b3c364"
author = ["Daniel Hopp <daniel.hopp1@gmail.com>"]
version = "0.0.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DataFrames = "≥ 0.20.0"
julia = "≥ 1.0.0"
Plots = "≥ 0.28.4"
